### ISSUE TITLE
Consider merging automatically PRs with only a version bump

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/rosdistro#17667]
Most rosdistro PRs are releases of a new version of an already released repo. It would save us a significant amount of time if the PRs that have only a 1 line diff that consists in a version bump were merged automatically

**Comment by tfoote** [comment]
I'm not sure how much time it actually costs us. I typically spend <10 seconds on those PRs and we only get less than 10 releases a day. And if we were to automate it we'd have to monitor it and have ways to disable it when we're in a sync period etc. With the extra overhead of managing another webhook and service and generally higher complexity would negate the time savings.

**Comment by wjwwood** [comment]
I don't mind one way or the other. I used to merge a lot of these, but lately I've been getting beat to them or I hesitate because I couldn't remember if we're doing a sync or not.

I tend to agree that they don't take up much time, but since I'm not the one merging most of them lately, I'd also be fine with automating the process.

**Comment by dirk-thomas** [comment]
Closing due to age and inactivity.
