### ISSUE TITLE
Header Error

### ISSUE THREAD

**Issue by Rafcin** [ros/rosdistro#19739]
Error:   Received an invalid TCPROS header.  Each line must have an equals sign.
         at line 102 in /tmp/binarydeb/ros-melodic-cpp-common-0.6.11/src/header.cpp
[ERROR] [1544908619.069775755]: Header from subscriber did not have the required elements: md5sum, topic, callerid

**Comment by tfoote** [comment]
This repository is for tracking issues with the ros distribution management. It sounds like you're not sure exactly where the error is coming from. I'd suggest that you ask for help on https://answers.ros.org

When you do so make sure to provide enough information to reproduce your problem so that we can help you. Only sharing the error is not enough to understand what caused it. Guidelines for asking questions can be found at https://wiki.ros.org/Support

**Comment by Rafcin** [comment]
I actually can't find anything about this, there isnt much on it...

**Comment by tfoote** [comment]
That's why I suggest that you ask for help on https://answers.ros.org and include enough information to reproduce your issue. Without understanding what is happening to cause the error all we can do is point to the line of code which is saying that there's an invalid header: https://github.com/ros/roscpp_core/blob/53fbad3599116e808d0865b0afbed8078acbbc3c/cpp_common/src/header.cpp#L102 If you provide more details there someone may be able to help you.
