### ISSUE TITLE
Rosdep failed running on docker image

### ISSUE THREAD

**Issue by SamLyuubc** [ros/rosdistro#22939]
Rosdep recently started failing after rosdep install && rosdep update with the following errors :

`
  ERROR: the following rosdeps failed to install
     apt: Failed to detect successful installation of [ros-melodic-map-server]
    apt: Failed to detect successful installation of [python3-catkin-pkg]
    apt: Failed to detect successful installation of [python3-rosdep]
`

Also, we noticed that running rosdep update uninstalls /usr/bin/catkin (by removing python-catkin-tools) and never installs it back even though catkin is specified in our package's list of dependencies.
 
This problem occurs during running a bitbucket pipeline using a docker image. We have used the same setup for a long time now but these failure only started happenning in the last 2 days. We are on Ubuntu and using ROS melodic. Can anyone help?

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

And when you do please make sure to provide enough information to reproduce your environment and problem. 
It's very unlikey that running `rosdep update` is actually adding or removing any packages. Since you're operating in a docker image you could even tag it and make it available for debugging.
