### ISSUE TITLE
libqglviewer-dev-qt4 on armhf

### ISSUE THREAD

**Issue by wxmerkt** [ros/rosdistro#23193]
octovis on dashing armhf fails as `libqglviewer-dev-qt4` cannot be resolved. This appears to be missing upstream. Can we blacklist the package then for armhf or what is the correct workaround?

**Comment by tfoote** [comment]
yeah, if a dependency like that is missing for a specific arch blacklisting it is our usual approach. We generally like to open an upstream ticket for reference and then open a PR blacklisting it so that it's visible why the package has disappeared. As an example: https://github.com/ros-infrastructure/ros_buildfarm_config/pull/126 where they resolve it and we reverted the blacklist.

**Comment by wxmerkt** [comment]
Thank you for the tutorial @tfoote.

I have opened pull requests for dashing (https://github.com/ros2/ros_buildfarm_config/pull/55) and eloquent (https://github.com/ros2/ros_buildfarm_config/pull/55).
