### ISSUE TITLE
replacing master/slave terminology with an alternative

### ISSUE THREAD

**Issue by trusktr** [ros/rosdistro#25516]
It may be more respectful for all possible users if the master/slave terminology is replaced with something else, like primary/assistant or something.

ref: http://wiki.ros.org/ROS/Master_Slave_APIs

Related: https://github.com/RethinkRobotics-opensource/rosnodejs/issues/151

:black_large_square:

**Comment by tfoote** [comment]
We've already made an effort to avoid using this terminology in several places in the ROS 1 codebase over the last several years. This particular instance is baked in deeply but is something that we have explicitly designed out of ROS 2. As such since ROS 1's final release, noetic, has already come out, this entire API will not be included in future ROS distributions. As such I would suggest that we consider this resolved since the terminology for this API will not be in any future rosdistro.

**Comment by dirk-thomas** [comment]
Assuming the previous comment answered the question I will go ahead and close this ticket for now. Please feel free to continue commenting.
