### ISSUE TITLE
Inconsistent libuv versions

### ISSUE THREAD

**Issue by stertingen** [ros/rosdistro#28399]
Currentliy, the key `libuv-dev` resolves either to `libuv0.10-dev` or `libuv1-dev` on Ubuntu and Debian: https://github.com/ros/rosdistro/blob/7060925/rosdep/base.yaml#L4498

These versions are not compatible. To resolve this issue, I see a few possibilities:
- Add key `libuv1-dev` and let `libuv-dev` point to `libuv-dev` or `libuv0.10-dev` if possible, otherwise `libuv1-dev`
- Add key `libuv0.10-dev` and let `libuv-dev` point to the latest available version

I would propose a PR when this discussion is resolved. (Including keys for recent Ubuntu version)

EDIT: For reference: https://packages.ubuntu.com/search?searchon=names&suite=all&section=all&keywords=libuv

**Comment by tfoote** [comment]
Yeah, those are different and it looks like the debian rules jumped forward too far to libuv1 in a bulk update: https://github.com/ros/rosdistro/pull/15349 which suggests it wasn't intentional. 

We should keep the existing keys consistent and pointing to the 0.10 version. And create new keys pointing to the 1.x versions

So keep `libuv-dev` and `libuv` -> 0.10 versions 
And create `libuv1-dev` and `libuv1` pointing to the 1.x versions.

That will maintain stability and support the newer versions. A PR to that effect would be appreciated.
