### ISSUE TITLE
How to add key for Jetson stats package

### ISSUE THREAD

**Issue by Prat33k-dev** [ros/rosdistro#28910]
Earlier my teammate @maarufvazifdar  added jetson-stats package https://pypi.org/project/jetson-stats/ but found that it is not working with rosdep. Also to install the package manually "pip install jetson-stats" does not work but "sudo -H pip install -U jetson-stats" works. So, how should I define it in the python.yaml file?
Reference for old PR- https://github.com/ros/rosdistro/pull/28280 
@tfoote  @dirk-thomas @wjwwood @mikaelarguedas

**Comment by tfoote** [comment]
Without more information "not working with rosdep" is hard for us to say what the problem is. If rosdep is invoking pip install and the installation is failing then you'll need to look into the package itself. It may not be mature enough to work consistently.

We don't support using the `-H` directive. That's relating to using the user's home directory which makes it user account specific which is not expected for a system installation. I tested it without the -H option and it seemed to install just fine. You also say that pip install doesn't work without the sudo. These both seem like issues to take up with the upstream package and are not something that we can help with.

**Comment by Prat33k-dev** [comment]
Ok, we will look into it. Thanks for the updates
