### ISSUE TITLE
Extend Gentoo CONTRIBUTING guides to clarify about pip rules 

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#29908]
This should be codified in the [CONTRIBUTING guide with respect to gentoo](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#gentoo) so that it's clear to contributors. As well as adding a comment/reference in the REVIEW_GUIDELINES to make it clear for the reviewers too.

https://github.com/ros/rosdistro/pull/29514#discussion_r636348684

@allenh1 Would you have a moment to suggest verbiage along the lines above so we don't have to ping you or find old references in cases like: https://github.com/ros/rosdistro/pull/29587

**Comment by allenh1** [comment]
Absolutely.

Just something along the lines of

"Pip cannot be used to install system packages on Gentoo, so if the package is not present in the Gentoo package repository, please create an issue on the ros/ros-overlay repository so that it may be created at a later date, omit the key from the new rosdep rule, and link the created issue in the PR which is adding the rule."

Please modify that as you see fit to be more succinct.
