### ISSUE TITLE
python-rdflib on ubuntu focal

### ISSUE THREAD

**Issue by McModknower** [ros/rosdistro#31337]
On ubuntu focal, the package `python-rdflib` doesn't exist.
However the `python-rdflib-tools` package replaces it.
in bionic it is still there.

Because the package no longer exists, there should be a rule for ubuntu focal near the following line:

https://github.com/ros/rosdistro/blob/782c1ce848006f0770a15117860add8ac4d98b04/rosdep/python.yaml#L4081

**Comment by tfoote** [comment]
Please consider opening a PR to update this. We rely on community submitted proposals to review. 

I see that you've referenced this already here: https://github.com/McModknower/rosdistro/commit/edd7eab78d4e63855869c50137ef775e859fa3f8

One note looking at that diff is that we want the newer versions to use the wildcard notation so that they're future compatible. And then you should explicitly call out the older versions that are still supported. And when the older versions go out of support we can just remove the explicit rules.
