### ISSUE TITLE
qpOASES vendor

### ISSUE THREAD

**Issue by mhubii** [ros/rosdistro#32362]
qpOASES vendor can't be linked against in ROS2, this includes foxy, galactic, rolling. The issue is caused by Autoware-AI/qpoases_vendor#5. qpOASES vendor should be removed from rosdistro until this issue is fixed

**Comment by tfoote** [comment]
We don't generally deindex packages because they have a bug in them.  There are likely workarounds that people can use in the meantime, and removing it from the distro will remove indexing, discoverability through cross referencing, and make it harder for people to find the bugs etc. If anything could be considered it would be a rollback to a known good version. But either way please reach out to the maintainer to resolve the issue. They will be the ones to fix it. I see that it already has a PR on it: https://github.com/Autoware-AI/qpoases_vendor/pull/6
