### ISSUE TITLE
[Question] pydantic from pip instead apt?

### ISSUE THREAD

**Issue by pariaspe** [ros/rosdistro#41050]
Would it be possible to change pydantic from apt to pip for every ubuntu distro? [apt version](https://launchpad.net/ubuntu/+source/pydantic) got stuck in an older version and it's not being updated.

https://github.com/ros/rosdistro/blob/0fb47463146b75e74481fb5c1a82709d6e2c7af9/rosdep/python.yaml#L7822-L7835

**Comment by clalancette** [comment]
> Would it be possible to change pydantic from apt to pip for every ubuntu distro? [apt version](https://launchpad.net/ubuntu/+source/pydantic) got stuck in an older version and it's not being updated.

No, because then we can't actually release packages that depend on `pydantic` onto the buildfarm (only packages that come from packages can be used on the buildfarm).

I think the best bet is to open an issue on the upstream Debian package and see if we can get some movement on it, which will eventually filter down into Ubuntu.

Because there is nothing to do here, I'm going to close this out.
