### ISSUE TITLE
Include the pyqtgraph plugin in the ROS repo

### ISSUE THREAD

**Issue by trainman419** [ros/rosdistro#4458]
The best plotting backend for rqt_plot is apparently pyqtgraph, and this is the backend that the rqt_plot developers use. Unfortunately, it isn't available in the Ubuntu repositories.

There's a pyqtgraph deb available on the [pyqtgraph site](http://www.pyqtgraph.org/). Is it possible to get it included in the ROS repository?

**Comment by mikaelarguedas** [comment]
@ros/team @trainman419 Is this still something of interest?
If no we could close this ticket, If yes, `python-pyqtgraph` is now available for all targeted platforms for Kinetic and Lunar so a rosdep key would be sufficient. If we want this in Indigo we will need to host them in the ROS apt repo.

**Comment by dirk-thomas** [comment]
Currently the [rqt_plot](https://github.com/ros-visualization/rqt_plot) repo uses a single branch for releases into all active ROS distros. We can either:

1. add a rosdep key for xenial and newer and create a kinetic and newer branch to it
2. add a rosdep key for all distros where older Ubuntu versions are empty, keep a single branch in rqt_plot
3. add a rosdep key for all distros, create and import .deb packages for older Ubuntu versions, keep a single branch in rqt_plot

If possible I would favor option 2 or 3 in order to avoid the extra effort for branching. I can do option 2 if we agree on that. For option 3 someone needs to take the initiative to create/import the .deb for older Ubuntu versions.

**Comment by mikaelarguedas** [comment]
I'm ok with option 2 if there is not a strong need in Indigo. It looks like this has been stale for a while so I'd expect that not having pyqtgraph support for indigo is acceptable.

Option 3 is definitely doable farily easily given that pyqtgraph provides their own debs and it's python only so importing that deb for all distros that don't have it should be straight forward.

**Comment by tfoote** [comment]
Option 3 looked good if we only had to do a backport for trusty. And it was available upstream. However, looking a little closer the packaged versions in the ubuntu repositories still depend on qt4 even for newer platforms (eg [xenial](https://packages.ubuntu.com/xenial/python-pyqtgraph) [artful](https://packages.ubuntu.com/artful/python-pyqtgraph)) But as of kinetic we switched to qt5 so I think we'll have to say that we can't support this until there's a qt5 version.
